version: "3"
services:
  nginx:
    build: ./nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql
      - php

  php:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION

volumes:
  mysql_data: {}
